version: "3"
services:
  ui:
    image: redocly/redoc
    container_name: ui
    volumes:
      - ./api.yml:/usr/share/nginx/html/api.yml
    environment:
      SPEC_URL: api.yml
    ports:
      - 8080:80
  mock:
    image: stoplight/prism:3
    container_name: mock
    ports:
      - 8081:4010
    command: mock -h 0.0.0.0 /api.yml
    volumes:
      - ./api.yml:/api.yml
